package io.github.aksworns22.wordlet.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// 동적 색을 못 쓰는 Android 12 미만에서 쓰는 색 구성.
// 기기의 동적 색과 같게 seed #6176AC를 Tonal Spot, 2025 spec으로 만든 값이다.

internal val LightColorScheme =
    lightColorScheme(
        primary = Color(0xFF4C5E8B),
        onPrimary = Color(0xFFF9F8FF),
        primaryContainer = Color(0xFFB9CBFF),
        onPrimaryContainer = Color(0xFF30436E),
        inversePrimary = Color(0xFFB9CBFF),
        secondary = Color(0xFF585F72),
        onSecondary = Color(0xFFF9F8FF),
        secondaryContainer = Color(0xFFDCE2F9),
        onSecondaryContainer = Color(0xFF4B5164),
        tertiary = Color(0xFF6B5780),
        onTertiary = Color(0xFFFFF6FF),
        tertiaryContainer = Color(0xFFE7CDFE),
        onTertiaryContainer = Color(0xFF56436A),
        background = Color(0xFFFAF8FE),
        onBackground = Color(0xFF30323A),
        surface = Color(0xFFFAF8FE),
        onSurface = Color(0xFF30323A),
        surfaceVariant = Color(0xFFE1E2ED),
        onSurfaceVariant = Color(0xFF5D5F68),
        surfaceTint = Color(0xFF4C5E8B),
        inverseSurface = Color(0xFF0D0E12),
        inverseOnSurface = Color(0xFF9D9CA2),
        error = Color(0xFFA83836),
        onError = Color(0xFFFFF7F6),
        errorContainer = Color(0xFFFA746F),
        onErrorContainer = Color(0xFF6E0A12),
        outline = Color(0xFF787A84),
        outlineVariant = Color(0xFFB0B1BC),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFAF8FE),
        surfaceContainer = Color(0xFFEDEDF6),
        surfaceContainerHigh = Color(0xFFE7E7F1),
        surfaceContainerHighest = Color(0xFFE1E2ED),
        surfaceContainerLow = Color(0xFFF4F3FA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD8D9E4),
        primaryFixed = Color(0xFFB9CBFF),
        primaryFixedDim = Color(0xFFABBDF0),
        onPrimaryFixed = Color(0xFF1C2F59),
        onPrimaryFixedVariant = Color(0xFF3A4C78),
        secondaryFixed = Color(0xFFDCE2F9),
        secondaryFixedDim = Color(0xFFCED4EB),
        onSecondaryFixed = Color(0xFF393F51),
        onSecondaryFixedVariant = Color(0xFF555B6E),
        tertiaryFixed = Color(0xFFE7CDFE),
        tertiaryFixedDim = Color(0xFFD9C0EF),
        onTertiaryFixed = Color(0xFF423056),
        onTertiaryFixedVariant = Color(0xFF604C74)
    )

internal val DarkColorScheme =
    darkColorScheme(
        primary = Color(0xFFB9C6EE),
        onPrimary = Color(0xFF323F61),
        primaryContainer = Color(0xFF455274),
        onPrimaryContainer = Color(0xFFDBE2FF),
        inversePrimary = Color(0xFF515E81),
        secondary = Color(0xFFC0C6DC),
        onSecondary = Color(0xFF394052),
        secondaryContainer = Color(0xFF353B4D),
        onSecondaryContainer = Color(0xFFB9BFD5),
        tertiary = Color(0xFFF1DFFF),
        onTertiary = Color(0xFF5F4B73),
        tertiaryContainer = Color(0xFFE7CDFE),
        onTertiaryContainer = Color(0xFF56436A),
        background = Color(0xFF0D0E12),
        onBackground = Color(0xFFE4E5F0),
        surface = Color(0xFF0D0E12),
        onSurface = Color(0xFFE4E5F0),
        surfaceVariant = Color(0xFF23262E),
        onSurfaceVariant = Color(0xFFA9AAB5),
        surfaceTint = Color(0xFFB9C6EE),
        inverseSurface = Color(0xFFFAF8FE),
        inverseOnSurface = Color(0xFF545559),
        error = Color(0xFFFA746F),
        onError = Color(0xFF490006),
        errorContainer = Color(0xFF871F21),
        onErrorContainer = Color(0xFFFF9993),
        outline = Color(0xFF73757F),
        outlineVariant = Color(0xFF454850),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF292C34),
        surfaceContainer = Color(0xFF18191F),
        surfaceContainerHigh = Color(0xFF1D1F26),
        surfaceContainerHighest = Color(0xFF23262E),
        surfaceContainerLow = Color(0xFF121318),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceDim = Color(0xFF0D0E12),
        primaryFixed = Color(0xFFC4D1FA),
        primaryFixedDim = Color(0xFFB6C3EB),
        onPrimaryFixed = Color(0xFF263354),
        onPrimaryFixedVariant = Color(0xFF435072),
        secondaryFixed = Color(0xFFDCE2F9),
        secondaryFixedDim = Color(0xFFCED4EB),
        onSecondaryFixed = Color(0xFF393F51),
        onSecondaryFixedVariant = Color(0xFF555B6E),
        tertiaryFixed = Color(0xFFE7CDFE),
        tertiaryFixedDim = Color(0xFFD9C0EF),
        onTertiaryFixed = Color(0xFF423056),
        onTertiaryFixedVariant = Color(0xFF604C74)
    )
