package io.github.aksworns22.wordlet.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// 앱 전체가 쓰는 색 구성.
// Android 17 에뮬레이터의 기본 동적 색 구성에서 그대로 읽어 온 값이다.

internal val LightColorScheme =
    lightColorScheme(
        primary = Color(0xFF4C5E8B),
        onPrimary = Color(0xFFF9F8FF),
        primaryContainer = Color(0xFFB9CBFF),
        onPrimaryContainer = Color(0xFF30436E),
        inversePrimary = Color(0xFFB8C6EE),
        secondary = Color(0xFF585F72),
        onSecondary = Color(0xFFF9F8FF),
        secondaryContainer = Color(0xFFDCE2F9),
        onSecondaryContainer = Color(0xFF4B5164),
        tertiary = Color(0xFF6B5780),
        onTertiary = Color(0xFFFFF6FF),
        tertiaryContainer = Color(0xFFE1C8F8),
        onTertiaryContainer = Color(0xFF523F67),
        background = Color(0xFFFAF8FE),
        onBackground = Color(0xFF30323A),
        surface = Color(0xFFFAF8FE),
        onSurface = Color(0xFF30323A),
        surfaceVariant = Color(0xFFE1E2ED),
        onSurfaceVariant = Color(0xFF5D5F68),
        surfaceTint = Color(0xFF4C5E8B),
        inverseSurface = Color(0xFF0D0E12),
        inverseOnSurface = Color(0xFFE4E5F0),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        outline = Color(0xFF787A84),
        outlineVariant = Color(0xFFB0B1BC),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFAF8FE),
        surfaceContainer = Color(0xFFEDEDF6),
        surfaceContainerHigh = Color(0xFFE7E7F1),
        surfaceContainerHighest = Color(0xFFE1E2ED),
        surfaceContainerLow = Color(0xFFF3F3FA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD8D9E4),
        primaryFixed = Color(0xFFB9CBFF),
        primaryFixedDim = Color(0xFFABBDF0),
        onPrimaryFixed = Color(0xFF1B2F59),
        onPrimaryFixedVariant = Color(0xFF394C78),
        secondaryFixed = Color(0xFFDCE2F9),
        secondaryFixedDim = Color(0xFFCED4EB),
        onSecondaryFixed = Color(0xFF383F51),
        onSecondaryFixedVariant = Color(0xFF555B6E),
        tertiaryFixed = Color(0xFFE1C8F8),
        tertiaryFixedDim = Color(0xFFD3BAEA),
        onTertiaryFixed = Color(0xFF3E2C52),
        onTertiaryFixedVariant = Color(0xFF5C4871)
    )

internal val DarkColorScheme =
    darkColorScheme(
        primary = Color(0xFFB8C6EE),
        onPrimary = Color(0xFF323F60),
        primaryContainer = Color(0xFF445274),
        onPrimaryContainer = Color(0xFFDAE3FF),
        inversePrimary = Color(0xFF4C5E8B),
        secondary = Color(0xFFC0C6DC),
        onSecondary = Color(0xFF394052),
        secondaryContainer = Color(0xFF353B4D),
        onSecondaryContainer = Color(0xFFB8BFD5),
        tertiary = Color(0xFFEDD8FF),
        onTertiary = Color(0xFF5B4870),
        tertiaryContainer = Color(0xFFE1C8F8),
        onTertiaryContainer = Color(0xFF523F67),
        background = Color(0xFF0D0E12),
        onBackground = Color(0xFFE4E5F0),
        surface = Color(0xFF0D0E12),
        onSurface = Color(0xFFE4E5F0),
        surfaceVariant = Color(0xFF23262E),
        onSurfaceVariant = Color(0xFFA9AAB5),
        surfaceTint = Color(0xFFB8C6EE),
        inverseSurface = Color(0xFFFAF8FE),
        inverseOnSurface = Color(0xFF30323A),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        outline = Color(0xFF73757F),
        outlineVariant = Color(0xFF454850),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF292C34),
        surfaceContainer = Color(0xFF17191F),
        surfaceContainerHigh = Color(0xFF1D1F26),
        surfaceContainerHighest = Color(0xFF23262E),
        surfaceContainerLow = Color(0xFF121318),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceDim = Color(0xFF0D0E12),
        primaryFixed = Color(0xFFB9CBFF),
        primaryFixedDim = Color(0xFFABBDF0),
        onPrimaryFixed = Color(0xFF1B2F59),
        onPrimaryFixedVariant = Color(0xFF394C78),
        secondaryFixed = Color(0xFFDCE2F9),
        secondaryFixedDim = Color(0xFFCED4EB),
        onSecondaryFixed = Color(0xFF383F51),
        onSecondaryFixedVariant = Color(0xFF555B6E),
        tertiaryFixed = Color(0xFFE1C8F8),
        tertiaryFixedDim = Color(0xFFD3BAEA),
        onTertiaryFixed = Color(0xFF3E2C52),
        onTertiaryFixedVariant = Color(0xFF5C4871)
    )
